{% set name = "cp2k-output-tools" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cp2k-output-tools-{{ version }}.tar.gz
  sha256: 336f98b2d44dbf7dd618b7bc7791af11b87d23e77a4cb90ae4042bdf1bced9f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - cp2k_bs2csv = cp2k_output_tools.scripts.bandstructure:cp2k_bs2csv
    - cp2k_pdos = cp2k_output_tools.scripts.pdos:cp2k_pdos
    - cp2kparse = cp2k_output_tools.cli:cp2kparse
    - xyz_restart_cleaner = cp2k_output_tools.trajectories.xyz_cli:xyz_restart_cleaner

requirements:
  host:
    - pip
    - poetry >=1
    - python >=3.6
  run:
    - dataclasses >=0.7,<1
    - numpy >=1.19,<2.0
    - python >=3.6
    - regex >=2020.1,<2021.0

test:
  imports:
    - cp2k_output_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cp2k/cp2k-output-tools
  summary: Python tools to handle CP2K output files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
